[package]
name = "smart_factory"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }      # For async support
serde = { version = "1.0.214", features = ["derive"] }  # For serializing and deserializing data structures
ros2-client = "0.7.5"